services:
  - type: web
    name: feefix-india
    runtime: python
    plan: free
    region: singapore
    branch: main
    buildCommand: pip install -r requirements.txtJ    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
